CREATE TABLE users(
id SERIAL PRIMARY KEY, 
username varchar(100) NOT NULL, 
password TEXT NOT NULL, 
email varchar(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts(
id SERIAL PRIMARY KEY, 
title VARCHAR(255) NOT NULL, 
content TEXT NOT NULL, 
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
id SERIAL PRIMARY KEY, 
content TEXT NOT NULL, 
post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE, 
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD CONSTRAINT unique_email UNIQUE(email);